# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: North Texas Presbytery (PCA)
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Home of the North Texas Presbytery of the Presbyterian Church in America (PCA).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ntpresby.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: ntpresby

denomination:
  name: Presbyterian Church in America
  acronym: PCA
  url: http://pcanet.org

# File settings
file_uploads: /workspace/uploads/files

# Build settings
markdown: kramdown

permalink: pretty


collections:
  churches:
    output: true
    permalink: /churches/:path/
  campusministries:
    output: true
    permalink: /campus-ministries/:path/
  committees:
    output: true
    permalink: /committees/:path/
  meetings:
    output: false
  homefeature:
    output: false
  news:
    output: false
